### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Vaults1** [Ad5001/SkriptPE#1]
You can port plugins? I mean, **CAN YOU**, not "wow it's possible to port plugins".

**Comment by Ad5001** [comment]
I'm not like taking the Java code and making it into PHP (even if they are really similar). I'mmakingit  from startch but with the Skript documentation ;)
(Btw is this your new account?)

**Comment by Vaults1** [comment]
Sorry for the late reply. I renamed my account.
