### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by majovec** [Ad5001/SkriptPE#2]
Please fix [01:26:47] [Server thread/CRITICAL]: Error: "Call to undefined method Ad5001\SkriptPE\Skript::getServer()" (EXCEPTION) in "/plugins/SkriptPE-master/src/Ad5001/SkriptPE/Skript" at line 37

**Comment by Ad5001** [comment]
This plugin is apart of my unfinished list.

**Comment by majovec** [comment]
oh :(
