### ISSUE TITLE
Pre compiled plugin?

### ISSUE THREAD

**Issue by 5mmx** [Ad5001/SkriptPE#3]
Hi is there an alredy-compiled version of the plugin? Also does this work like normal skript plugin for java version?

**Comment by Ad5001** [comment]
Hi,
I'm sorry but this plugin is apart of my unfinished list.

**Comment by 5mmx** [comment]
Oh. So this plugin is not developed anymore?

**Comment by Ad5001** [comment]
Yes indeed, it was never finished in the first place due to the amount of work required to do it. Sorry if you had hopes it might work (I should mark this repo as non-working).

**Comment by 5mmx** [comment]
:(
